public enum FieldType
{
    FIRST_PLAYER_HAND,
    FIRST_PLAYER_HAND_FRONT_FIELD,
    FIRST_PLAYER_HAND_BACK_FIELD,
    SECOND_PLAYER_HAND_HAND,
    SECOND_PLAYER_HAND_HAND_FRONT_FIELD,
    SECOND_PLAYER_HAND_HAND_BACK_FIELD
}